# Logging
logging:
  level:
    ROOT: info
    at.jku.dke: trace

# Data
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/etutor_xquery
    username: etutor_xquery
    password: secret
  jpa:
    show-sql: true

# API key definition
clients:
  api-keys:
    - name: task-administration
      key: task-admin-key
      roles:
        - CRUD
        - SUBMIT
    - name: jobe-server
      key: jobe-server-key
      roles:
        - SUBMIT
    - name: plag-check
      key: plag-check-key
      roles:
        - READ_SUBMISSION

# XQuery
xquery:
  executor: basex
  xml-directory: ./basex
