name: 💉 Failing test
description: Report failing tests or CI jobs.
title: "[Test]: "
labels: ["Type: Test", "Status: Triage"]
body:
  - type: textarea
    id: tests
    attributes:
      label: Which job(s)/test(s) are failing?
      description: The CI jobs or tests that are failing.
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason for failure/description
      description: Try to describe why the test is failing or what we are missing to make it pass.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
