# Releases the App
name: Release App

# Run on merged pull request
on:
  pull_request:
    types:
      - closed

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && startsWith(github.event.pull_request.title, 'chore(publish):')
    steps:
      - name: Checkout Starter Library
        uses: actions/checkout@v4
        with:
          repository: eTutor-plus-plus/task-app-starter
          ref: main
          path: starter

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: app

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install Starter Library with Maven
        working-directory: starter
        run: mvn clean install --file pom.xml

      - name: Clean and Compile with maven
        working-directory: app
        run: mvn -B clean git-commit-id:revision spring-boot:build-info compile --file pom.xml

      - name: Build with Maven
        working-directory: app
        run: mvn -B package -DskipTests --file pom.xml

      - name: Split PR title
        env:
          MSG: ${{ github.event.pull_request.title }}
        id: split
        run: echo "VERSION=${MSG##*v}" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/target/*.jar
            app/pom.xml
          tag_name: "v${{ steps.split.outputs.VERSION }}"
          prerelease: ${{ contains(github.event.pull_request.title, '-') }}
          generate_release_notes: true
          draft: true
          fail_on_unmatched_files: false
